[[seed]]
url = "http://localhost:6060"
ajax = false

[[target]]
pattern = "http://localhost:6060/cmd/*" # /regexp/ or glob pattern
frequence = "10s"
priority = 1.0

# how to find target
[[filter]]
pattern = "http://localhost:6060/cmd*"
score = 1024
[[filter]]
pattern = "http://localhost:6060/*"
score = 512
[[filter]]
pattern = "*"
score = 0

store = "db"
frequence = "once"
